# dbt_project.yml

name: 'dbt_project_2'
version: '1.0.0'
profile: 'jaffle_shop'

vars:
  snowflake_schemas:
    - name: CONFIGS
    - name: RAW_DATA
    - name: STG_PIM
    - name: STG_SAP
    - name: ANALYTICS

  snowflake_file_formats:
    - name: CSV_FORMAT_DEFAULT
      options: |
        TYPE = CSV
        FIELD_DELIMITER = ','
        SKIP_HEADER = 1
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
        TRIM_SPACE = TRUE
    - name: CSV_NO_HEADER
      options: |
        TYPE = CSV
        FIELD_DELIMITER = ','
        SKIP_HEADER = 0
        TRIM_SPACE = TRUE
    - name: JSON_FORMAT_STRIP_OUTER_ARRAY
      options: |
        TYPE = JSON
        STRIP_OUTER_ARRAY = TRUE
        ALLOW_DUPLICATE = FALSE
    - name: PARQUET_FORMAT_DEFAULT
      options: |
        TYPE = PARQUET

  snowflake_stages:
    - name: S3_QUICKSTART
      url: 's3://sfquickstarts/tastybytes/'
      file_format_ref: CSV_FORMAT_DEFAULT
    - name: AZURE_DATA_LAKE_EXAMPLE
      url: 'azure://azuresnowflake.blob.core.windows.net/testdata/'
      file_format_ref: PARQUET_FORMAT_DEFAULT
    - name: MY_PRIVATE_S3_STAGE
      url: 's3://my-private-bucket/data/'
      file_format_ref: CSV_NO_HEADER

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
# --- IMPORTANT CHANGE HERE: Added "macros/utils" to macro-paths ---
macro-paths: ["macros", "macros/utils"]
# --- End of change ---
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  jaffle_shop: # This is your project name
    example:
      +materialized: view
