dbt_snowflake_project_1:
target: dev
outputs:
  dev:
    type: snowflake
    account: 'not needed'
    user: 'not needed'
    role: accountadmin
    database: DBT_HOL_DEV
    schema: public
    warehouse: dbt_dev_wh
  prod:
    type: snowflake
    account: 'not needed'
    user: 'not needed'
    role: accountadmin
    database: DBT_HOL_PROD
    schema: public
    warehouse: dbt_prod_wh
