# config/table_definitions/stg_pim_tables.yml

# Tables for the STG_PIM schema
tables:
  - name: MENU_new1
    schema: STG_PIM # This table will go into DBT_DEV.STG_PIM
    columns:
      - name: MENU_ID
        type: NUMBER(19,0)
      - name: MENU_TYPE_ID
        type: NUMBER(38,0)
      - name: MENU_TYPE
        type: VARCHAR(16777216)
      - name: TRUCK_BRAND_NAME
        type: VARCHAR(16777216)
      - name: MENU_ITEM_ID
        type: NUMBER(38,0)
      - name: MENU_ITEM_NAME
        type: VARCHAR(16777216)
      - name: ITEM_CATEGORY
        type: VARCHAR(16777216)
      - name: ITEM_SUBCATEGORY
        type: VARCHAR(16777216)
      - name: COST_OF_GOODS_USD
        type: NUMBER(38,4)
      - name: SALE_PRICE_USD
        type: NUMBER(38,4)
      - name: MENU_ITEM_HEALTH_METRICS_OBJ
        type: VARIANT
    file_path: 'raw_pos/menu/menu.csv.gz' # The specific path on the stage
    file_format_ref: CSV_FORMAT_DEFAULT # Reference to a format in config/file_formats.yml
    stage_name_ref: S3_QUICKSTART # Reference to a stage in config/stages.yml
    # NEW: Specific COPY INTO options for this table
    copy_options: |
      ON_ERROR = 'CONTINUE'
      PURGE = FALSE # Example of another common copy option

  - name: MENU_new2
    schema: STG_PIM # This table will go into DBT_DEV.STG_PIM
    columns:
      - name: MENU_ID
        type: NUMBER(19,0)
      - name: MENU_TYPE_ID
        type: NUMBER(38,0)
      - name: MENU_TYPE
        type: VARCHAR(16777216)
      - name: TRUCK_BRAND_NAME
        type: VARCHAR(16777216)
      - name: MENU_ITEM_ID
        type: NUMBER(38,0)
      - name: MENU_ITEM_NAME
        type: VARCHAR(16777216)
      - name: ITEM_CATEGORY
        type: VARCHAR(16777216)
      - name: ITEM_SUBCATEGORY
        type: VARCHAR(16777216)
      - name: COST_OF_GOODS_USD
        type: NUMBER(38,4)
      - name: SALE_PRICE_USD
        type: NUMBER(38,4)
      - name: MENU_ITEM_HEALTH_METRICS_OBJ
        type: VARIANT
    file_path: 'raw_pos/menu/menu.csv.gz' # The specific path on the stage
    file_format_ref: CSV_FORMAT_DEFAULT # Reference to a format in config/file_formats.yml
    stage_name_ref: S3_QUICKSTART # Reference to a stage in config/stages.yml
    # NEW: Specific COPY INTO options for this table
    copy_options: |
      ON_ERROR = 'CONTINUE'
      PURGE = FALSE # Example of another common copy option